### ISSUE TITLE
Add `$NPM_TOKEN` to repo secrets

### ISSUE THREAD

**Issue by jcbhmr** [jcbhmr/geolocation-api.js#1]
Need to make the [release-created workflow] work.

```yml
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # <---- Needs $NPM_TOKEN in repo secrets
```

[release-created workflow]: https://github.com/jcbhmr/geolocation-api.js/blob/main/.github/workflows/release-created.yml
